version: "3"

services:
  kakao-sync-api: 
    image: kakao-sync-api:0.1
  kakao-sync-web:
    image: kakao-sync-web:0.1
    volumes:
      - ./nginx/web/nginx.conf:/etc/nginx/nginx.conf
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy/nginx.conf:/etc/nginx/nginx.conf